### PR TITLE
feat: icons support

### PR DESCRIPTION
**Pull request by dlvhdr**
https://user-images.githubusercontent.com/6196971/215571496-d678b9ef-d2ad-4b72-99a3-8675adaa55ec.mov

### CODE REVIEW

**Comment by antonmedv** [comment]
Awesome! What about adding this support via env LLAMA_ICONS=true instead on `--icons`?

**Comment by dlvhdr** [comment]
I was thinking of adding a couple more flags in the future like:
- `--group-directories-first`
- `--colo[u]r=WHEN    when to use terminal colours (always, auto, never)`

These flags come from [exa](https://github.com/ogham/exa) and are really useful for me.

If you like these additional flags, having an env variable will not scale IMHO.
wdyt?

**Comment by dlvhdr** [comment]
I use the `ll` alias, so I can just pass there all the flags.
Other people can also add such flags under an alias.
If you prefer env variables I can do that but flags seems cleaner to me.

**Comment by antonmedv** [comment]
> I use the ll alias so cd works, so I can just pass there all the flags.


Make sense. 


Flags are okay :)

**Comment by antonmedv** [comment]
BTW, will you be able to generate gif the same way as in https://github.com/antonmedv/llama/tree/master/.github/images ? Using vhs.

**Comment by dlvhdr** [comment]
Yeah vhs is awesome

**Comment by dlvhdr** [comment]
Cool, so if you're good with the PR feel free to merge :)

**Comment by antonmedv** [comment]
Can you also generate the gif?

**Comment by dlvhdr** [comment]
@antonmedv done!

**Comment by antonmedv** [comment]
Awesome thanks! Let’s also add this gif in examples in README with instructions on how to install icons.

**Comment by dlvhdr** [comment]
Done :) Let me know if that's ok

**Pull request merged**
