### PR TITLE
Vim mode

### LINKED ISSUE #2: Support vim key bindings
Add a configurable option to replace directional arrow keys with `hjkl`;

> set LLAMA_VIM_KEYBINDINGS=true

### PR DESCRIPTION
**Pull request by meowgorithm**
This update enables Vim keybindings when `LLAMA_VIM_KEYBINDINGS=true` is set.

Vim mode uses <kbd>hjkl</kbd> for navigation by default. Search-to-match can be activated with <kbd>/</kbd> and deactivated with <kbd>esc</kbd>. When search-to-match is active <kbd>esc</kbd> to quit is disabled and an indicator appears in the view.

This PR is based on https://github.com/antonmedv/llama/pull/8, however I'm implementing this separately because of the addition of the keymap (from [`Bubbles`](https://github.com/charmbracelet/bubbles#key)), which I believe simplifies the code.

Closes #2.

### CODE REVIEW

**Comment by meowgorithm** [comment]
Note: found and fixed a few small edge cases but we should otherwise be ready to go here. Totally open to feedback as well.

**Comment by antonmedv** [comment]
Awesome 👏🏻

**Comment by antonmedv** [comment]
Just thought, what about making vim mode the default?

**Comment by meowgorithm** [comment]
@antonmedv Yep, totally into that.

**Comment by portothree** [comment]
This is awesome!
Can we have a new release tag for this? Looking to test this change with Nix on `nixpkgs` and it relies on releases to bump the version

**Pull request merged**
