### PR TITLE
Add vim key bindings hjkl

### LINKED ISSUE #2: Support vim key bindings
Add a configurable option to replace directional arrow keys with `hjkl`;

> set LLAMA_VIM_KEYBINDINGS=true

### PR DESCRIPTION
**Pull request by kencx**
Adds support for `hjkl`. Closes #2.

Fuzzy search mode is activated with `/` and deactivated with `Esc`. Changing directories also deactivates it.

For now, this is a breaking change. Making it configurable with `export LLAMA_VIM_KEYBINDINGS=true` seems to require multiple switch case statements, which is quite messy imo. Unless there is a better way?

Note: The git diff seems to have gone wonky after nesting the switch statement within an else.

### CODE REVIEW

**Comment by antonmedv** [comment]
Current mode should also be available.

**Comment by antonmedv** [comment]
> which is quite messy imo. 

So this is a challenge. Add feature and simply code.

**Comment by kencx** [comment]
Managed to implement configurable vim mode.

Any feedback is appreciated :)

**Comment by kencx** [comment]
Updated with the recent changes.

**Comment by antonmedv** [comment]
Done!

**Pull request closed without merging**
