### PR TITLE
Update Bubble Tea to v0.23.0 and Lip Gloss to v0.6.0

### PR DESCRIPTION
**Pull request by meowgorithm**
This also means we can remove the manual color profile detection as Lip Gloss will now properly detect the color profile over `stderr` per https://github.com/charmbracelet/bubbletea/issues/172.

### CODE REVIEW

**Comment by antonmedv** [comment]
Awesome 👍

**Comment by antonmedv** [comment]
for some reason this is not working for me and now llama don't have any colors.

**Comment by meowgorithm** [comment]
Sorry about that. Fixed in https://github.com/antonmedv/llama/pull/27.

**Comment by antonmedv** [comment]
It's okay! Thanks for the awesome project! =)

**Pull request merged**
