### PR TITLE
Feature add - Context Menu

### PR DESCRIPTION
**Pull request by habitualdev**
Adds a spacebar powered context menu, with the following options:
<br>
select - Focuses on a file for move and copy operations
copy - copies the selected file to the currently browsed directory
move - moves the selected file to the currently browsed directory
delete - runs "rm -rf" on the currently focused file/directory
settings - directly opens ~/.llamarc 
<br>

This is facilitated by the addition of a bool to the model, "contextMenu". Based on the value of this new bool, it selects for different actions for select keys (Up, down, enter, spacebar). 

At this time, the options are scrolled through, but only one is displayed at a time.

Context Menu screenshot attached.
ContextMenu

### CODE REVIEW

**Comment by antonmedv** [comment]
This is not really looking good. I think we can work on better design.

**Comment by roaldi** [comment]
For sure. I'll rework the context menu to be more visually appealing. Are you ok in general with the " different page" design? I tried messing around with forcing bubbletea to do a drop-down style menu on the list view, but it ended up breaking the ui more often than not. 

Additionally, thoughts on how llamarc is implemented?

**Comment by roaldi** [comment]
Updated the context menu to reflect the base look.

updatedUI

**Comment by roaldi** [comment]
Remediated conflicts from the recent PR's

**Comment by roaldi** [comment]
Should I change to .llama from .llamarc, or wait on the bubbletea update?

**Comment by antonmedv** [comment]
Let’s wait bubble tea first. Lots of bugs we will encounter otherwise.

**Comment by antonmedv** [comment]
Let’s implement something more terminal style.

**Pull request closed without merging**
